"""add email_verified to users

Revision ID: b83c54d634a3
Revises: 8ffe90f20f50
Create Date: 2026-10-04 13:46:46.829408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83c54d634a3'
down_revision = '8ffe90f20f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'active', name='user_status_enum'), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
